import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const projectRoot = path.resolve(__dirname, '..')
const vocabularyPath = path.join(projectRoot, 'src', 'data', 'vocabulary.json')
const outputPath = path.join(projectRoot, 'supabase', 'vocabulary_seed.sql')

function escapeSqlText(value) {
  return String(value ?? '').replace(/'/g, "''")
}

function sqlText(value) {
  return `'${escapeSqlText(value)}'`
}

function sqlJson(value) {
  const json = JSON.stringify(value ?? null)
    // Supabase SQL Editor may split multi-statement queries on literal semicolons
    // inside long string payloads, so encode them for JSON parsing on insert.
    .replace(/;/g, '\\u003B')

  return `'${escapeSqlText(json)}'::jsonb`
}

async function main() {
  const raw = await fs.readFile(vocabularyPath, 'utf8')
  const rows = JSON.parse(raw)

  const values = rows.map((item, index) => {
    return `(
  ${sqlText(item.word)},
  ${sqlText(item.fullForm || item.word)},
  ${sqlText(item.category || 'other')},
  ${sqlText(item.difficulty || '')},
  ${sqlText(item.partOfSpeech || '')},
  ${sqlText(item.phonetic || '')},
  ${sqlText(item.audio || '')},
  ${sqlJson(item.translations || {})},
  ${sqlText(item.description || '')},
  ${sqlText(item.englishDefinition || '')},
  ${sqlText(item.example || '')},
  ${sqlJson(item.meanings || [])},
  ${sqlJson(item.codeExamples || [])},
  ${index + 1}
)`
  })

  const sql = `-- Auto-generated by scripts/generate_supabase_vocabulary_seed.mjs
-- Source: src/data/vocabulary.json

insert into public.vocabulary (
  word,
  full_form,
  category,
  difficulty,
  part_of_speech,
  phonetic,
  audio,
  translations,
  description,
  english_definition,
  example,
  meanings,
  code_examples,
  sort_order
)
values
${values.join(',\n')}
on conflict (word) do update set
  full_form = excluded.full_form,
  category = excluded.category,
  difficulty = excluded.difficulty,
  part_of_speech = excluded.part_of_speech,
  phonetic = excluded.phonetic,
  audio = excluded.audio,
  translations = excluded.translations,
  description = excluded.description,
  english_definition = excluded.english_definition,
  example = excluded.example,
  meanings = excluded.meanings,
  code_examples = excluded.code_examples,
  sort_order = excluded.sort_order;
`

  await fs.writeFile(outputPath, sql, 'utf8')
  console.log(`Generated ${outputPath}`)
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
